--A1 - 
-- CREATE TABLE IF NOT EXISTS STUDENT (
--     ROLL_NO TEXT PRIMARY KEY,
--     NAME TEXT NOT NULL,
--     ADDRESS TEXT,
--     PHONE TEXT,
--     AGE INTEGER
-- );

-- INSERT INTO STUDENT(ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
-- ('1', 'RAM', 'DELHI', '*********', 18),
-- ('2', 'RAMESH', 'GURGAON', '********', 18),
-- ('3', 'SUJIT', 'ROHTAK', '*********', 20),
-- ('4', 'SURESH', 'DELHI', '*********', 18),
-- ('5', 'AMAN', 'ROHTAK', '*********', 20),
-- ('6', 'HARSH', 'GURGAON', '*********', 18),

-- SELECT * FROM STUDENT;

-- SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'DELHI';

-- SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'RAM';

-- SELECT * FROM STUDENT WHERE NAME = 'RAM' OR NAME = 'SUJIT';

-- SELECT * FROM STUDENT WHERE NAME = 'RAM' OR AGE = 20;

-- SELECT * FROM STUDENT WHERE AGE = 18 AND (NAME = 'RAM' OR NAME = 'RAMESH');

-- A2 -

-- CREATE TABLE IF NOT EXISTS PRODUCT (
--     PRO_ID TEXT PRIMARY KEY,
--     PRO_NAME TEXT,
--     PRO_PRICE TEXT,
--     PRO_COM TEXT
-- );

-- INSERT INTO PRODUCT(PRO_ID,PRO_NAME,PRO_PRICE,PRO_COM)

-- VALUES

-- ("101","MOTHER BOARD","3200","15"),

-- ("102","KEY BOARD","450","16"),

-- ("103","ZIP DRIVE","250","14"),

-- ("104","SPEAKER","550","16"),

-- ("105","MONITOR","5000","11"),

-- ("106","DVD DRIVE","900","12"),

-- ("107","CD DRIVE","800","12"),

-- ("108","PRINTER","2600","13"),

-- ("109","REFILL CARTRIDGE","350","13"),

-- ("110","MOUSE","250","12");

-- SELECT PRO_NAME, PRO_PRICE FROM PRODUCT WHERE PRO_PRICE = (SELECT MIN(PRO_PRICE) FROM PRODUCT);

-- SELECT PRO_NAME, PRO_PRICE FROM PRODUCT WHERE PRO_PRICE = (SELECT MAX(PRO_PRICE) FROM PRODUCT);